# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
customer_input = "first_environment"
git_url        = "git::https://github.com/Steve-CrateDefense/git-workflow-presentation.git"
unit_tag       = "main"
value1         = "default_value1"
value2         = "default_value2"
